apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docs-index
  namespace: astra
  labels:
    app: docs
    component: documents-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: fast-ssd  # Uncomment and set your storage class
