apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: astra-data-pvc
  namespace: astra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: standard
