apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: your-service
  namespace: production
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: your-service
  service:
    port: 8001
    targetPort: 8001
    name: your-service
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration-p95
        thresholdRange:
          max: 2500
        interval: 1m
      - name: error-rate
        thresholdRange:
          max: 1
        interval: 1m
